name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_API_URL_V2: ${{ secrets.NEXT_PUBLIC_API_URL_V2 }}
        run: npm run build

      - name: Compress build result
        run: |
          tar -czf build.tar.gz .next public package.json

      - name: Copy build file to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_PROD_HOST }}
          username: ${{ secrets.EC2_PROD_USER }}
          key: ${{ secrets.EC2_PROD_KEY }}
          source: 'build.tar.gz'
          target: '/home/${{ secrets.EC2_PROD_USER }}/deploy/build.tar.gz'

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_PROD_HOST }}
          username: ${{ secrets.EC2_PROD_USER }}
          key: ${{ secrets.EC2_PROD_KEY }}
          script: |
            DEPLOY_PATH="/var/www/erp-front"

            mkdir -p $DEPLOY_PATH

            # 압축 해제
            tar -xzf ~/deploy/build.tar.gz -C $DEPLOY_PATH

            rm ~/deploy/build.tar.gz

            # pm2 restart 또는 시작
            pm2 restart erp-front || pm2 start npm --name "erp-front" -- start

            sudo systemctl reload nginx
