name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 소스 체크아웃
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Node 설정
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4️⃣ 환경파일 생성 및 빌드
      - name: Create .env.production and Build
        run: |
          echo "NEXT_PUBLIC_API_URL=https://erp-api.dooson.it/api/v1" > .env.production
          echo "NEXT_PUBLIC_API_URL_V2=https://erp-api.dooson.it/api/v2" >> .env.production
          npm run build

      # 5️⃣ 빌드 압축
      - name: Compress build result
        run: |
          tar -czf build.tar.gz .next public package.json

      # 6️⃣ EC2로 파일 전송
      - name: Copy build file to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_PROD_HOST }}
          username: ${{ secrets.EC2_PROD_USER }}
          key: ${{ secrets.EC2_PROD_KEY }}
          source: 'build.tar.gz'
          target: '/home/${{ secrets.EC2_PROD_USER }}/deploy/build.tar.gz'

      # 7️⃣ EC2 배포 및 Nginx 설정
      - name: Deploy on EC2 and Configure Nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_PROD_HOST }}
          username: ${{ secrets.EC2_PROD_USER }}
          key: ${{ secrets.EC2_PROD_KEY }}
          script: |
            DEPLOY_PATH="/var/www/erp-front"
            DOMAIN="erp.dooson.it"

            # 1️⃣ 배포 경로 생성
            sudo mkdir -p $DEPLOY_PATH
            sudo chown -R $USER:$USER $DEPLOY_PATH

            # 2️⃣ 압축 해제
            tar -xzf ~/deploy/build.tar.gz -C $DEPLOY_PATH
            rm -f ~/deploy/build.tar.gz

            pm2 startOrReload ecosystem.config.js
            pm2 save


            # 4️⃣ Nginx 설정 자동화
            sudo tee /etc/nginx/sites-available/erp-front > /dev/null <<'EOF'
            server {
                listen 80;
                server_name erp.dooson.it;

                location / {
                    proxy_pass http://localhost:3000;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host $host;
                    proxy_cache_bypass $http_upgrade;
                }
            }
            EOF

                        # 심볼릭 링크
                        sudo ln -sf /etc/nginx/sites-available/erp-front /etc/nginx/sites-enabled/erp-front

                        # Nginx 문법 확인 후 재시작
                        sudo nginx -t
                        sudo systemctl reload nginx
